spring.datasource.url=${DEV_DATABASE_URL}
spring.datasource.username=${DEV_DATABASE_USERNAME}
spring.datasource.password=${DEV_DATABASE_PASSWORD}

jwt.secret=${DEV_JWT_SECRET}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true